spring:
  application:
    name: coupon
  config:
    activate:
      on-profile: dev
server:
  port: 8070


logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}


#swagger 설정
springdoc:
  packages-to-scan: store.novabook
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

---
spring:
  cloud:
    openfeign:
      client:
        config:
          store-service:
            url: http://localhost:9777/api/v1/store

---
rabbitmq:
  queue:
    couponCreateNormal: nova.coupon.create.normal.queue
    couponCreateHighTraffic: nova.coupon.create.hightraffic.queue
    couponRegisterNormal: nova.coupon.register.normal.queue
    couponRegisterHighTraffic: nova.coupon.register.hightraffic.queue
    deadLetter: nova.coupon.deadletter.queue
  exchange:
    couponOperation: nova.coupon.operation.exchange
    deadLetter: nova.coupon.deadletter.exchange
  routing:
    couponCreateNormal: coupon.create.normal
    couponCreateHighTraffic: coupon.create.hightraffic
    couponRegisterNormal: coupon.register.normal
    couponRegisterHighTraffic: coupon.register.hightraffic
