spring:
  config:
    activate:
      #      개인 테스트 환경
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: supernova
    password: 1234
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 3000 # 최초 메시지 처리 실패 후 재시도까지의 인터벌 (3초)
          max-interval: 10000 # 최대 재시도 인터벌 (10초)
          max-attempts: 3 # 최대 재시도 횟수
          multiplier: 2.0 # 이전 interval * multiplier = 다음 interval

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


rabbitmq:
  queue:
    coupon: couponQueue
    retry: retryQueue
    dead: deadQueue
  exchange:
    member: memberExchange
  routing:
    member: member.registration