spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000 # 최초 메시지 처리 실패 후 재시도까지의 인터벌 (3초)
          max-interval: 10000 # 최대 재시도 인터벌 (10초)
          max-attempts: 3 # 최대 재시도 횟수
          multiplier: 2.0 # 이전 interval * multiplier = 다음 interval

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource  # 사용할 데이터 소스 타입 (DBCP2)
    dbcp2:
      initial-size: 10  # 처음 풀(pool)에 할당할 커넥션 개수
      max-total: 50
      max-idle: 50  # 풀에 유지할 수 있는 최대 유휴 커넥션 개수
      min-idle: 10  # 풀에 유지할 최소 유휴 커넥션 개수
      validation-query: SELECT 1  # 커넥션 유효성 검사를 위한 쿼리
      default-auto-commit: true  # 기본 자동 커밋 설정

  #절대 변경 금지
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#유레카 활성화
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      couponKey: 62954fd4bba04501a7059459ae11a56d
      redisKey: 60427297022b4bdb9650789537e4b945
      rabbitMQKey: 5070b197613e4db6a73e9db96c54789f
      userAccessKey: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
