spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000  # 최초 메시지 처리 실패 후 재시도까지의 인터벌 (3초)
          max-interval: 10000    # 최대 재시도 인터벌 (10초)
          max-attempts: 3        # 최대 재시도 횟수
          multiplier: 2.0        # 이전 interval * multiplier = 다음 interval

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  file:
    path: ${user.dir}

#유레카 활성화
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      redisKey: 60427297022b4bdb9650789537e4b945
      rabbitMQKey: 57e5b5f62b404b58b7a7cc79352d5d82
      userAccessKey: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt
