spring:
  config:
    activate:
      #      개인 테스트 환경
      on-profile: local
  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000  # 최초 메시지 처리 실패 후 재시도까지의 인터벌 (3초)
          max-interval: 10000    # 최대 재시도 인터벌 (10초)
          max-attempts: 3        # 최대 재시도 횟수
          multiplier: 2.0        # 이전 interval * multiplier = 다음 interval

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  file:
    path: ${user.dir}



rabbitmq:
  queue:
    coupon: nova.coupon.queue
    dead: nova.dead.queue
    member-coupon: nova.membercoupon.queue
  exchange:
    member: nova.member.exchange
    coupon: nova.coupon.exchange
  routing:
    member: member.registration
    couponCreated: coupon.created

store:
  service:
    url: http://localhost:9777/api/v1/store

#유레카 활성화
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true