spring:
  config:
    activate:
      #      개인 테스트 환경
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace