spring:
  config:
    activate:
      #      개인 테스트 환경
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: supernova
    password: 1234

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


rabbitmq:
  queue:
    coupon: couponQueue
  exchange:
    member: memberExchange
  routing:
    member: member.registration