spring:
  application:
    name: coupon
  profiles:
    active: prod
server:
  port: 8070


logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}

---
spring:
  cloud:
    openfeign:
      client:
        config:
          store-service:
            url: http://localhost:9777/api/v1/store
