### 모든 쿠폰 조회
POST http://localhost:8080/api/v1/coupons
Content-Type: application/json

{
  "couponIdList": [
    1,
    2,
    3
  ]
}

### 쿠폰 생성
POST http://localhost:8080/api/v1/coupons
Content-Type: application/json

{
  "couponTemplateId": 123
}

### 쿠폰 사용
PUT http://localhost:8080/api/v1/coupons/{couponId}

### 쿠폰 템플릿 생성
POST http://localhost:8070/api/v1/coupon-templates
Content-Type: application/json

{
  "name": "신규 사용자 할인",
  "type": "WELCOME",
  "discountAmount": 5000,
  "discountType": "AMOUNT",
  "maxDiscountAmount": 5000,
  "minPurchaseAmount": 20000,
  "startedAt": "2023-12-01T00:00:00",
  "expirationAt": "2025-01-01T00:00:00",
  "usePeriod": 30
}

### 일반 쿠폰 템플릿 생성
POST http://localhost:8070/api/v1/coupon-templates
Content-Type: application/json

{
  "name": "일반 할인 쿠폰",
  "type": "GENERAL",
  "discountAmount": 3000,
  "discountType": "AMOUNT",
  "maxDiscountAmount": 3000,
  "minPurchaseAmount": 15000,
  "startedAt": "2023-12-01T00:00:00",
  "expirationAt": "2025-01-01T00:00:00",
  "usePeriod": 30
}

### 생일 쿠폰 템플릿 생성
POST http://localhost:8070/api/v1/coupon-templates
Content-Type: application/json

{
  "name": "생일 축하 할인 쿠폰",
  "type": "BIRTHDAY",
  "discountAmount": 20,
  "discountType": "PERCENT",
  "maxDiscountAmount": 10000,
  "minPurchaseAmount": 5000,
  "startedAt": "2023-12-01T00:00:00",
  "expirationAt": "2024-01-01T00:00:00",
  "usePeriod": 7
}



### 모든 쿠폰 템플릿 조회
GET http://localhost:8080/api/v1/coupon-templates?page=0&size=10&type=WELCOME

### 모든 책 쿠폰 템플릿 조회 (페이지네이션 적용)
GET http://localhost:8080/api/v1/book-coupon-templates?page=0&size=10
Accept: application/json


### 새로운 책 쿠폰 템플릿 생성
POST http://localhost:8070/api/v1/book-coupon-templates
Content-Type: application/json
Accept: application/json

{
  "bookId": 5,
  "name": "할인 쿠폰",
  "discountAmount": 10,
  "discountType": "PERCENT",
  "maxDiscountAmount": 10000,
  "minPurchaseAmount": 20000,
  "startedAt": "2024-03-01T00:00:00",
  "expirationAt": "2024-12-31T23:59:59",
  "usePeriod": 30
}


### 특정 책 ID로 쿠폰 템플릿 조회 (유효성 여부 필터 적용)
GET http://localhost:8080/api/v1/book-coupon-templates/book/1?isValid=true
Accept: application/json

### 모든 카테고리 쿠폰 템플릿 조회 (페이지네이션 적용)
GET http://localhost:8080/api/v1/category-coupon-templates?page=0&size=10
Accept: application/json

###

### 특정 카테고리 ID로 쿠폰 템플릿 조회 (유효성 여부 필터 적용)
GET http://localhost:8080/api/v1/category-coupon-templates/category/1?isValid=true
Accept: application/json

###

### 새로운 카테고리 쿠폰 템플릿 생성
POST http://localhost:8070/api/v1/category-coupon-templates
Content-Type: application/json
Accept: application/json

{
  "categoryId": 5,
  "name": "할인 쿠폰ㅎㅇㅎㅇ",
  "discountAmount": 20,
  "discountType": "PERCENT",
  "maxDiscountAmount": 10000,
  "minPurchaseAmount": 20000,
  "startedAt": "2024-07-01T00:00:00",
  "expirationAt": "2024-12-31T23:59:59",
  "usePeriod": 30
}

### Get Sufficient Coupons
POST http://localhost:8070/api/v1/coupons/sufficient
Content-Type: application/json

{
  "couponIdList": [
    1,
    2,
    3
  ],
  "bookIdList": [
    10,
    20,
    30
  ],
  "categoryIdList": [
    100,
    200,
    300
  ]
}

###
