### Create a new birthday coupon with current and future date
POST http://localhost:8070/api/v1/coupon/coupons/general
Content-Type: application/json

{
  "couponType": "BIRTHDAY",
  "name": "Birthday Discount",
  "discountAmount": 1000,
  "discountType": "AMOUNT",
  "maxDiscountAmount": 5000,
  "minPurchaseAmount": 2000,
  "startedAt": "2024-06-23T00:00:00",
  "expirationAt": "9999-12-31T23:59:59",
  "usePeriod": 30
}

### Get all general coupons with default pagination
GET http://localhost:8070/api/v1/coupon/coupons/general

### Get all general coupons with specific pagination
GET http://localhost:8070/api/v1/coupon/coupons/general?page=0&size=5
