name: Deploy to NHN Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Build with Maven
        run: mvn clean verify

      - name: Test code
        run: mvn test

      - name: Deploy to NHN Cloud
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Add SSH key
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          # Copy files to server
          scp -i private_key -o StrictHostKeyChecking=no -r * $SERVER_USER@$SERVER_IP:/home/nova-dev/coupon
          # SSH into server and restart application
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /home/nova-dev/coupon
            # Application-specific deployment commands
            ./restart.sh
          EOF
