name: Deploy to NHN Cloud

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Deploy JAR on Remote Server
        env:

          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
          chmod 400 ~/.ssh/github_rsa
          ssh-keyscan ${SERVER_IP} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} << 'EOF'
          ps aux | grep coupon-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9
          cd /home/nova-dev/coupon
          nohup java -jar coupon-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF