name: Deploy to NHN Cloud

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Build with Maven
        run: mvn clean verify

      - name: Test code
        run: mvn test

      - name: Upload JAR to Remote Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no mkdir -p /home/.ssh
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no echo "${SSH_PRIVATE_KEY}" > /home/.ssh/github_rsa
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no chmod 400 ~/.ssh/github_rsa
          ssh-keyscan ${SERVER_IP} >> ~/.ssh/known_hosts
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no target/*.jar ${SERVER_USER}@${SERVER_IP}:/home/nova-dev/coupon

      - name: Deploy to NHN Cloud
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no -r * ${SERVER_USER}@${SERVER_IP}:/home/nova-dev/coupon
          ssh -i private_key -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} << 'EOF'
          ssh -i private_key -o StrictHostKeyChecking=no cd /home/nova-dev/coupon
          ssh -i private_key -o StrictHostKeyChecking=no ./restart.sh
          EOF
